name: Extra Fancy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: deps
      run: python -m pip install flake8 pylint black
    - name: lint
      run: make lint
    - name: test
      run: make test
      env:
        PYTHONPATH: /home/runner/work/aoc2022/aoc2022/
